### ISSUE TITLE
Report tweaks

### ISSUE THREAD

**Issue by whmacken** [FLNRO-Smithers-Research/PortfolioKiri#11]
- [x] might as next issue. Need to rescript the portfolio_function script to allow changes to number of time periods considered - changing the timePeriod variable leads to many mis-matches in the code as hardwired to use all future periods

- [x] Error in current portfolio for some BGCs where only one time period has the species (?) or something where only one value and cannot be extrapolated.

- [x] Transpose the model parameter table with species as columns. Need row names for min and max. and make the table caption in the chunk header rather than on the actual tabel

- [x] Reduce size of legend in portfolio graphs - to long in some cases.

- [ ] Add caption title to portfolio in the knitr chunk

- [x] Add in the line type to the legend (or in caption)

- [x] The estimated site index seems like it it the mean SI where the species occurs. But it should probably mean SI over all 30 futures. (then Ss in the CDFmm would be really low I assume)

- [x] Use ClimateBC6.3 for the climate data if you have not already

- [x] The model parameters could be at the bottom of the report and include the min/max weight, the minimum threshold weight to be included, and the time frame of the portfolio (to 2040, 2070, or 2100)

- [x] Can the portions of the stacked BGC bars be labelled directly with the BGC code? Hard to easily interpret by referring to the legend by colour

**Comment by kdaust** [comment]
Pertaining to the first bullet, I think it's actually ok. With the simulation, we're doing a time period of 100 years, regardless of what time periods we're actually using data for.

**Comment by whmacken** [comment]
OK. It dies for me for some reason though

**Comment by kdaust** [comment]
Yep, I'm on it. Is any input data you changed in the git repo?
