### ISSUE TITLE
Error establishing cluster for parallel

### ISSUE THREAD

**Issue by whmacken** [FLNRO-Smithers-Research/PortfolioKiri#7]
Error in checkForRemoteErrors(lapply(cl, recvResult)) : 6 nodes produced errors; first error: file not found: 'D:/GitHub/Portfolio_CCISS/CBSTPortfolio/CppFunctions/SimGrowth.cpp'
I get this error when running r parallel chunk

**Comment by kdaust** [comment]
Hmm. I just ran the whole script and it works fine for me. I've added some comments and cleaned up old files - try again making sure you're using the PortfolioScript_PythonCpp.R and let me know if it works. It seems like there was a directory issue where the script couldn't find the Cpp script to source.
